# CI for PuzzleBox.Timeline
# Build > Test > Pack > Push

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  Major: '0'
  Minor: '1'
  Patch: '1'

steps:

# Build
- script: dotnet build -c $(buildConfiguration)
  displayName: 'Build'

# Test - TODO

# Pack
- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: pack
    configuration: 'release'
    packagesToPack: PuzzleBox.Timeline/PuzzleBox.Timeline.csproj
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'

# Push
#- task: NuGetCommand@2
#  displayName: 'Push'
#  inputs:
#    command: push
#    nuGetFeedType: external
#    publishFeedCredentials: 'PuzzleBox.Timeline'
#    packagesToPack: PuzzleBox.Timeline/PuzzleBox.Timeline.csproj
